// Generated by CoffeeScript 1.6.3
var FizzBuzz;

FizzBuzz = (function() {
  function FizzBuzz() {}

  FizzBuzz.prototype.run = function(n) {
    var result;
    result = "";
    if (n % 3 === 0) {
      result += "Fizz";
    }
    if (n % 5 === 0) {
      result += "Buzz";
    }
    return result;
  };

  return FizzBuzz;

})();

module.exports.FizzBuzz = FizzBuzz;
