// Generated by CoffeeScript 1.6.3
var Greeting;

Greeting = (function() {
  function Greeting() {}

  Greeting.prototype.greet = function() {
    return "hello";
  };

  Greeting.prototype.say = function(message) {
    return message;
  };

  return Greeting;

})();

module.exports.Greeting = Greeting;
