// Generated by CoffeeScript 1.6.3
var MovieLibrary;

module.exports = MovieLibrary = (function() {
  function MovieLibrary() {
    this.movies = [];
  }

  MovieLibrary.prototype.add = function(movie) {
    if (!this.contains(movie)) {
      return this.movies.push(movie);
    }
  };

  MovieLibrary.prototype.total_count = function() {
    return this.movies.length;
  };

  MovieLibrary.prototype.contains = function(other_movie) {
    var result,
      _this = this;
    result = false;
    this.each(function(movie) {
      return result || (result = movie.title === other_movie.title);
    });
    return result;
  };

  MovieLibrary.prototype.each = function(visitor) {
    var movie, _i, _len, _ref, _results;
    _ref = this.movies;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      movie = _ref[_i];
      _results.push(visitor(movie));
    }
    return _results;
  };

  return MovieLibrary;

})();
