// Generated by CoffeeScript 1.6.3
var MovieLibrary,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

module.exports = MovieLibrary = (function() {
  function MovieLibrary() {
    this.movies = [];
  }

  MovieLibrary.prototype.add = function(movie) {
    if (__indexOf.call(this.movies, movie) < 0) {
      return this.movies.push(movie);
    }
  };

  MovieLibrary.prototype.total_count = function() {
    return this.movies.length;
  };

  return MovieLibrary;

})();
