// Generated by CoffeeScript 1.6.3
var Movie;

module.exports = Movie = (function() {
  function Movie(attributes) {
    this.title = attributes['title'];
  }

  Movie.prototype.equals = function(other) {
    return this.title === other["title"];
  };

  return Movie;

})();
