// Generated by CoffeeScript 1.6.3
var Studio;

module.exports = Studio = {
  CastleRock: "Castle Rock",
  MiramaxFilms: "Miramax Films",
  RegencyEnterprises: "Regency Enterprises",
  Pixar: "Pixar",
  Disney: "Disney"
};
